i\AppBundle\Entity\Login:
    type: entity
    table: login
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: SEQUENCE
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        email:
            type: string
            length: 255
            fixed: false
            nullable: false
        password:
            type: string
            length: null
            fixed: true
            nullable: false
        salt:
            type: string
            length: 255
            fixed: false
            nullable: false
        pics:
            type: integer
            unsigned: false
            nullable: false
        facebookId:
            type: bigint
            nullable: true
            column: facebook_id
    lifecycleCallbacks: {  }
