i\AppBundle\Entity\Pic:
    type: entity
    table: pic
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: SEQUENCE
        loginId:
            type: integer
            unsigned: false
            nullable: false
            column: login_id
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        url:
            type: text
            nullable: false
        likes:
            type: integer
            unsigned: false
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks: {  }
