security:
    encoders:
        i\AppBundle\Entity\Login:
            algorithm:        sha512
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        logins:
            entity: { class: iAppBundle:Login, property: email }

    firewalls:
        global:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
                use_forward: false
                use_referer: false
                always_use_default_target_path: false
            logout:
                path: /logout
                target: /
                invalidate_session: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

