<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130710161438 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // ./app/console doctrine:migrations:diff

        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE pic ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL");
        $this->addSql("ALTER TABLE pic ALTER id DROP DEFAULT");
        $this->addSql("ALTER TABLE pic ALTER likes SET ");
        $this->addSql("ALTER TABLE login ALTER id DROP DEFAULT");
        $this->addSql("ALTER TABLE login ALTER pics SET ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE login_id_seq");
        $this->addSql("SELECT setval('login_id_seq', (SELECT MAX(id) FROM login))");
        $this->addSql("ALTER TABLE login ALTER id SET DEFAULT nextval('login_id_seq')");
        $this->addSql("ALTER TABLE login ALTER pics SET  DEFAULT 0");
        $this->addSql("ALTER TABLE pic DROP created_at");
        $this->addSql("CREATE SEQUENCE pic_id_seq");
        $this->addSql("SELECT setval('pic_id_seq', (SELECT MAX(id) FROM pic))");
        $this->addSql("ALTER TABLE pic ALTER id SET DEFAULT nextval('pic_id_seq')");
        $this->addSql("ALTER TABLE pic ALTER likes SET  DEFAULT 0");
    }
}
